### ISSUE TITLE
更改文件名后出现 404

### ISSUE THREAD

**Issue by run-ze** [YongHaoWu/qianduan-yule-club#12]
@YongHaoWu 
把 fontend.css 重命名为 frontend.css，并相应修改 index.html。
一小时后，访问 qianduanyule.club 时，frontend.css 得到404，页面样式丢失。
而且通过手动输入 URL 可以看到 fontend.css 依然存在。

**Comment by atlas-comstock** [comment]
@run-ze  因为我是简单用 crontab来 `cp index.html fontend.css` 到 nginx 的指定目录，所以 typo 依然存在，不会同步到那里去
我现在已经增加了 frontend.css 的规则，你可以 revert 回去了

**Comment by atlas-comstock** [comment]
@run-ze  因为是这样子的，所以有目录结构，或者文件更改等的时候，需要我来做更新。

**Comment by run-ze** [comment]
@YongHaoWu 这样 merge => revert => revert revert 是不是不太好？
应该怎么样处理比较好？

**Comment by atlas-comstock** [comment]
@run-ze  我平常要不就这样，要不就 push --force..
