### ISSUE TITLE
给我权限吧！

### ISSUE THREAD

**Issue by run-ze** [YongHaoWu/qianduan-yule-club#7]
每次 PR 都要等你同意，太慢了。

**Comment by atlas-comstock** [comment]
@run-ze 大佬，好的，没问题！！！感谢！

**Comment by atlas-comstock** [comment]
@run-ze  权限已给。目前我是 用 git pull 拉下静态网页， 然后 cp 覆盖 nginx 里的。
要不要我跑个 cron，10分钟做一遍这个动作？反正机子也是闲着。

**Comment by run-ze** [comment]
@YongHaoWu 多谢。

**Comment by atlas-comstock** [comment]
*/5 * * * * /home/yonghaohu/projects/qianduan-yule-club/update.sh

@run-ze  每5分钟会自动拉，然后 update 静态文件。
